version: '3.8'

services:
  turtlebot_pc:
    image: osrf/ros:noetic-desktop-full
    build: .
    container_name: turtlebot_brain
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - ROS_MASTER_URI=http://10.110.46.31:11311
      - ROS_HOSTNAME=10.110.46.31 # Set this to your laptop's actual IP
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros_home:/root  # Maps your local code to the container
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  turtlebot_data:
